jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v1
    - continue-on-error: true
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: build
      run: ./gradlew :library:build --stacktrace
name: Android CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
